### ISSUE TITLE
mp3/mp4 support

### ISSUE THREAD

**Issue by tanosuggests** [vampiricwulf/tanoshiine#51]

**Comment by vampiricwulf** [comment]
mp3: 0998e17bb1159fb977d16cf9e0163b154971afd0
ogg and mp4 later.

**Comment by seastones** [comment]
http://stackoverflow.com/questions/6239350/how-to-extract-duration-time-from-ffmpeg-output

This might prove useful for grabbing lengths of arbitrary audio file types.

**Comment by seastones** [comment]
We should restrict it to ones we can use in browsers directly which leaves MP3, OGG, WAV.

Maybe MP4 if that won't cause issues when someone uploads a video in an MP4 container.

**Comment by seastones** [comment]
Also, one of the posts on that StackOverflow thread mentioned MediaInfo might be easier to use to grab information like that. It looks like it ought to work for those formats.
http://mediaarea.net/nn/MediaInfo
