### ISSUE TITLE
Working backwards from meguca

### ISSUE THREAD

**Issue by vampiricwulf** [vampiricwulf/tanoshiine#85]
AKA: I'm better at taking steps backwards than forward :^)
- [ ] Toggleable Banner
  - [ ] TESTED
- [x] Our Banner Icons
  - [x] TESTED
- [ ] Static Banner (not r/a/dio) [Top and Bottom]
  - [ ] TESTED
- [x] Spectrograms for non-artwork audio files
  - [x] TESTED
    - [ ] `<abbr>` css
    - [ ] WAV
    - [ ] OGG
- [x] Pushbullet reports
  - [x] TESTED
    - [ ] socket hang up (still completes though)
- [ ] New Icons
  - [ ] TESTED
- [ ] Animated loading
  - [ ] TESTED
- [ ] Themes
  - [ ] TESTED
- [x] Volume Controller
  - [x] TESTED
- [x] Beep
  - [x] TESTED

**Comment by bakape** [comment]
> Spectrograms for non-artwork audio files

Blue is reportedly working on no-artwork MP3 and deduplication. But knowing him, that could take a while. You should drop in /g/, that's where most of the dev talk happens. Also, if any questions arise.

**Comment by vampiricwulf** [comment]
Ohho? I was also thinking about [Identicons](https://en.wikipedia.org/wiki/Identicon). What do you think about that?

**Comment by bakape** [comment]
Needs to be benchmarked. I don't want to add too much overhead. And a static thumbnail is always an option.

**Comment by vampiricwulf** [comment]
I see, I was keeping duplicates in mind, since I currently have no idea how you even handle them with album artwork. /tano/s would post albums at a time, so the spectrogram was to keep the duplication in check.

**Comment by bakape** [comment]
Duplicates are a non-issue. I'll let Blue handle it. I'm more concerned on what to put on MP3s with no covers.

**Comment by vampiricwulf** [comment]
Discontinued

**Comment by bakape** [comment]
>killing off a piece off history

**Comment by vampiricwulf** [comment]
It had to be done, the historical landmarks must be killed. The code was made during a time of oppression and thus was upsetting my feelings!

Nah but for real if I was to go work backwards from meguca again, using such ancient code would just be a bad idea since any bugs you found woulda been patched by now and there'd be so many newer features. Since tano is still somehow running with its spaghetti code and Reiner performed major updates to get us on newer Nodejs versions, my interest is just be going back to pushing tano forward with features rather than pulling backwards features from meguca.
