### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by tanosuggests** [vampiricwulf/tanoshiine#99]
Does this still work?

**Comment by vampiricwulf** [comment]
> Hi @tanosuggests,
> 
> On July 15th, 2020 at 00:43 (UTC) you used a password to access an endpoint through the GitHub API using NodeJS HTTP Client:
> 
> https://api.github.com/repositories/19795229/issues
> 
> Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team
